### ISSUE TITLE
Could not retrieve index file for bam file

### ISSUE THREAD

**Issue by GMFranceschini** [lhqing/cemba_data#23]
Good morning, I was almost able to complete the run of snakemake for the snm3C protocol based on single cell fastqs downloaded from SRA. However, I encountered this error in the very last step. Could you please advise? Thank you

```
[Fri Nov  8 10:51:40 2024]
rule generate_contact:
    input: bam/SRR8994460.3C.sorted.bam
    output: hic/SRR8994460.3C.contact.tsv.gz, hic/SRR8994460.3C.contact.tsv.counts.txt
    jobid: 8
    wildcards: cell_id=SRR8994460
    resources: mem_mb=300

# Executing generate-contacts...
[E::idx_find_and_load] Could not retrieve index file for 'bam/SRR8994460.3C.sorted.bam'
Traceback (most recent call last):
  File "/cso/gscratch/gianmarco/tools/miniforge3/envs/mapping/bin/yap-internal", line 8, in <module>
    sys.exit(internal_main())
  File "/cso/gscratch/gianmarco/tools/miniforge3/envs/mapping/lib/python3.7/site-packages/cemba_data/_yap_internal_cli_.py", line 636, in internal_main
    func(**args_vars)
  File "/cso/gscratch/gianmarco/tools/miniforge3/envs/mapping/lib/python3.7/site-packages/cemba_data/mapping/m3c/__init__.py", line 178, in generate_contacts
    split_table_path = _parse_bam(bam_path=bam_path, output_path=split_table_path)
  File "/cso/gscratch/gianmarco/tools/miniforge3/envs/mapping/lib/python3.7/site-packages/cemba_data/mapping/m3c/__init__.py", line 103, in _parse_bam
    locs[split_dict[split_st]] = f'1:' \
KeyError: '1/1-l-1'

```

Trying manual indexing results in an error, as the bam file is not sorted as the name suggests.

**Comment by GMFranceschini** [comment]
More on that, if I then attempt to index I get:

```
[E::hts_idx_push] Unsorted positions on sequence #12: 68439311 followed by 68439271
samtools index: failed to create an index for "SRR8994460.3C.ssorted.bam"
```

Sorting without the flag works smoothly - but a bam sorted by name should work too. Do you think read names could cause any problems?

Below are the header and a sample of the file, from your mouse brain study.


```
samtools view -H SRR8994460.3C.sorted.bam
@HD	VN:1.0	SO:queryname
@SQ	SN:chr10	LN:130694993
@SQ	SN:chr11	LN:122082543
@SQ	SN:chr12	LN:120129022
@SQ	SN:chr13	LN:120421639
@SQ	SN:chr14	LN:124902244
@SQ	SN:chr15	LN:104043685
@SQ	SN:chr16	LN:98207768
@SQ	SN:chr17	LN:94987271
@SQ	SN:chr18	LN:90702639
@SQ	SN:chr19	LN:61431566
@SQ	SN:chr1	LN:195471971
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr3	LN:160039680
@SQ	SN:chr4	LN:156508116
@SQ	SN:chr5	LN:151834684
@SQ	SN:chr6	LN:149736546
@SQ	SN:chr7	LN:145441459
@SQ	SN:chr8	LN:129401213
@SQ	SN:chr9	LN:124595110
@SQ	SN:chrM	LN:16299
@SQ	SN:chrX	LN:171031299
@SQ	SN:chrY	LN:91744698
@PG	ID:Bismark	VN:v0.20.0	CL:"bismark /cso/gscratch/iGenomes/bismark_bw1/mm10/ -un --bowtie1 fastq/SRR8994460-R1.trimmed.fq.gz --pbat -o bam/ --temp_dir bam/"
@PG	ID:Bismark-4091ADCA	VN:v0.20.0	CL:"bismark /cso/gscratch/iGenomes/bismark_bw1/mm10/ --bowtie1 bam/SRR8994460-R1.trimmed.fq.gz_unmapped_reads.split.fq.gz --pbat -o bam/ --temp_dir bam/"
@PG	ID:Bismark-2F44A643	VN:v0.20.0	CL:"bismark /cso/gscratch/iGenomes/bismark_bw1/mm10/ -un --bowtie1 fastq/SRR8994460-R2.trimmed.fq.gz -o bam/ --temp_dir bam/"
@PG	ID:Bismark-73327C72	VN:v0.20.0	CL:"bismark /cso/gscratch/iGenomes/bismark_bw1/mm10/ --bowtie1 bam/SRR8994460-R2.trimmed.fq.gz_unmapped_reads.split.fq.gz -o bam/ --temp_dir bam/"
```

```
samtools view SRR8994460.3C.sorted.bam | head
SRR8994460.1_1/1-l	16	chr2	68438995	255	40M	*	0	0	TTAAATATGAAATATAACCTAAAAACTATTTAAATGAAAT	FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFF:FFF	NM:i:12	MD:Z:2G1G1G2G10G1G1G2G3G0G0G2G3	XM:Z:..h.h.h.Hh..........x.h.h..x...hhh.Hh...	XR:Z:GA	XG:Z:GA
SRR8994460.1_1/1-m	16	chr2	68439035	255	40M	*	0	0	AACTCCTTCCCTCTCTAAACTACTCTAACCGTAATACTAT	FFFFF:FFFF:FFFFFF:FFFFFFFFFFFF:FFFF::FFF	NM:i:8	MD:Z:0G17G2G4G0G4G0G1G4	XM:Z:h.................h..x....xh..Z.hh.h....XR:Z:GA	XG:Z:GA
SRR8994460.1_1/1-r	16	chr2	68439075	255	40M	*	0	0	AACATAACACTAAAAATCCTACCTAACCCTCCATCTGTGT	F,FFFFF:FF::,FF:FFFF:FFFFFFFF:FFFFFFFF:F	NM:i:4	MD:Z:1G4G5G12G14	XM:Z:.h....h.....h............h..........X.H.XR:Z:GA	XG:Z:GA
SRR8994460.1_1/2-m	16	chr2	68439311	255	39M	*	0	0	CATCAAATATATATAAATACATACACACACATACACACA	,FFFF,:FFFFFFFF,,FFF,F,F:FFFFF,FFFFFFFF	NM:i:0	MD:Z:39	XM:Z:.......................................	XR:Z:CT	XG:Z:GA
SRR8994460.1_1/2-r	16	chr2	68439271	255	40M	*	0	0	TTATTTCTTAAATTATCCTTTTACCTACAATATTCACCCT	:FFFFFF:FFFFFFFFF,F:FFFFF,F,F:F,FFFF:FFF	NM:i:2	MD:Z:9G12G17	XM:Z:.........h............h.................	XR:Z:CT	XG:Z:GA
SRR8994460.2_2/1	0	chr1	152045518	255	131M	*	0	0	CGTTTGAAAAGAGAAAGGTAAGGGTTGTGTGTTTGGGTAATTATAGACGGTTCGAGATCATTTTTAGTTTTTTAATTTTTAATATAATCGTAAAAGAAAATTGTTTGTTTAGTGTGGTTTTTTGAAGGTTA	:F,FFFFF:FFFFF,FFFFFFFFFFFFFFFFFFFF:FFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NM:i:30	MD:Z:3C20C7C7C2C6C0C5C2C2C0C2C1C0C6C0C3C1C2C12C3C2C1C7C0C0C0C0C6C0C1	XM:Z:Z..x....................x.......x.......h..x...Z..hxZ....hH.h..hx..h.hh......hh...h.h..xZ...........x...x..h.x.......hhhhx......hh.	XR:Z:GA	XG:Z:CT
SRR8994460.2_2/2-m	0	chr1	152045847	255	41M	*	0	0	TATAATTTTTTAATCGATAGATAATTTGAGGGAGGTAGTTT	FFFFFF,FF::FFF::F:F:,FFF,FFFF::FFF,:FFFF,	NM:i:7	MD:Z:6C0C2C6C2T0C18C0	XM:Z:......hh..h...Z..x...h..................h	XR:Z:CT	XG:Z:CT
SRR8994460.2_2/2-r	0	chr1	152045888	255	40M	*	0	0	TTTTCGTTTATTATGTGGGTTTTAGGATTAAATTTTTGGT	FFFFF,FFFFFFFF,FFFFFFFF:F:FFFFFF:FFFF:FF	NM:i:11	MD:Z:1C1C3C2C0C9C0C5C3C0C1C4	XM:Z:.h.xZ..h..hh.........hx.....h...hh.x....	XR:Z:CT	XG:Z:CT
SRR8994460.3_3/1	16	chr2	32572293	255	129M	*	0	0	CCAACCATTCATTAACAACCAACATATCATCCACAAATACTTCCTACCCCGCGCCTACGCCGTCCTCCTCCCGTTAACCGCAAACCTCCTACTACTCCTATTTATAAATAAATCTCCCGATCTAAAACA	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF:FF:FFFFFF:FF:FF:FFFFFFFFFFFFF:FFFFFFFF:FFFFFFF:F:,F:,FF	NM:i:21	MD:Z:3G9G3G3G3G19G29G0G5G0G6G2G9G1G0G0G3G11G0G0G0G2	XM:Z:...x.........h...x...x...h...................x....Z.Z.....Z..Z..........Z..hh..Z..xh......x..x.........h.hhh...h......Z....xhhh..	XR:Z:GA	XG:Z:GA
SRR8994460.3_3/2-m	16	chr2	32572495	255	41M	*	0	0	ATACTCCCCGAAACTTTCCTATTCCTTAAAAACCACAAACA	:FFFFFFFFFFFFFFFFFFF:F:FFFFFFFFFFFFFFFFFF	NM:i:9	MD:Z:2G7G0G0G17G0G4G0G0G2	XM:Z:..h......Zxhh.................hh....zxh..	XR:Z:CT	XG:Z:GA
```

**Comment by GMFranceschini** [comment]
Indeed this was again a problem of the version of `pysam` not being pinned.
This update introduced breaking changes - causing the loading of bam files to get stuck if no index is present

See: https://github.com/pysam-developers/pysam/issues/939
